[project]
name = "dungeon-crawler-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cholotamo", email = "cholorafaeltamo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "google-genai>=2.20.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
dungeon-crawler-text = "dungeon_crawler_text:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
